apiVersion: v1
kind: Service
metadata:
  name: fl-aggregator
  namespace: fl-platform
  labels:
    app: fl-aggregator
    app.kubernetes.io/part-of: federated-learning
    app.kubernetes.io/component: aggregator
spec:
  type: ClusterIP
  selector:
    app: fl-aggregator
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
