apiVersion: v1
kind: Service
metadata:
  name: fl-frontend
  namespace: fl-platform
  labels:
    app: fl-frontend
    app.kubernetes.io/part-of: federated-learning
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: fl-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
